var imageDataTags = [
    {"id": 100, "name": "No collision"},
    {"id": 101, "name": "Has collision"},
    {"id": 102, "name": "Upwarp"},
    {"id": 103, "name": "Achievement"},
    {"id": 104, "name": "Allied Seals"},
    {"id": 105, "name": "Beast Tribe"},
    {"id": 106, "name": "Bicolor Gemstone"},
    {"id": 107, "name": "Bozjan Cluster"},
    {"id": 108, "name": "Camera block"},
    {"id": 109, "name": "SFX Carpet"},
    {"id": 110, "name": "Centurio Seals"},
    {"id": 111, "name": "Company Cred"},
    {"id": 112, "name": "Company Credits"},
    {"id": 113, "name": "Cowrie"},
    {"id": 114, "name": "Crafted"},
    {"id": 115, "name": "SFX Dirt"},
    {"id": 116, "name": "Doze"},
    {"id": 117, "name": "Dye"},
    {"id": 118, "name": "Eternal Bond"},
    {"id": 119, "name": "Event"},
    {"id": 120, "name": "FATE"},
    {"id": 121, "name": "Furnishing"},
    {"id": 122, "name": "GC Seals"},
    {"id": 123, "name": "Gil Vendor"},
    {"id": 124, "name": "SFX Grass"},
    {"id": 125, "name": "Heaven on High"},
    {"id": 126, "name": "Kupo of Fortune"},
    {"id": 127, "name": "SFX Leaf"},
    {"id": 128, "name": "Limit 1"},
    {"id": 129, "name": "Limit 196"},
    {"id": 130, "name": "Limit 2*"},
    {"id": 131, "name": "Limit 20"},
    {"id": 132, "name": "Limit 2-4*"},
    {"id": 133, "name": "Limit 4-10*"},
    {"id": 134, "name": "Loot"},
    {"id": 135, "name": "Market Board"},
    {"id": 136, "name": "SFX Metal"},
    {"id": 137, "name": "MGP"},
    {"id": 138, "name": "Mog Station"},
    {"id": 139, "name": "No Void Jump"},
    {"id": 140, "name": "Order Bonus"},
    {"id": 141, "name": "Phase 0"},
    {"id": 142, "name": "Phase 1"},
    {"id": 143, "name": "Phase 2"},
    {"id": 144, "name": "Phase 3"},
    {"id": 145, "name": "Phase 4"},
    {"id": 146, "name": "Phase 5"},
    {"id": 147, "name": "Phase 6"},
    {"id": 148, "name": "Phase 7"},
    {"id": 149, "name": "Phase 8"},
    {"id": 150, "name": "PvP Reward"},
    {"id": 151, "name": "Quick Venture"},
    {"id": 152, "name": "Raid"},
    {"id": 153, "name": "Rathalos Scale"},
    {"id": 154, "name": "Rug"},
    {"id": 155, "name": "Sil'dihn Manuscript"},
    {"id": 156, "name": "Silver Certificate"},
    {"id": 157, "name": "Sit"},
    {"id": 158, "name": "Skybuilder's Scrip"},
    {"id": 159, "name": "SFX Stone"},
    {"id": 160, "name": "Submarine"},
    {"id": 161, "name": "Table"},
    {"id": 162, "name": "Tabletop"},
    {"id": 163, "name": "Tomestones"},
    {"id": 164, "name": "Trophy Crystal"},
    {"id": 165, "name": "Wall-mounted"},
    {"id": 166, "name": "SFX Water"},
    {"id": 167, "name": "White Scrip"},
    {"id": 168, "name": "Wolf Marks"},
    {"id": 169, "name": "SFX Wood"},
];